// Generated by gencpp from file gopher_move_it_config/Joints.msg
// DO NOT EDIT!


#ifndef GOPHER_MOVE_IT_CONFIG_MESSAGE_JOINTS_H
#define GOPHER_MOVE_IT_CONFIG_MESSAGE_JOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gopher_move_it_config
{
template <class ContainerAllocator>
struct Joints_
{
  typedef Joints_<ContainerAllocator> Type;

  Joints_()
    : joints()  {
    }
  Joints_(const ContainerAllocator& _alloc)
    : joints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::gopher_move_it_config::Joints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gopher_move_it_config::Joints_<ContainerAllocator> const> ConstPtr;

}; // struct Joints_

typedef ::gopher_move_it_config::Joints_<std::allocator<void> > Joints;

typedef boost::shared_ptr< ::gopher_move_it_config::Joints > JointsPtr;
typedef boost::shared_ptr< ::gopher_move_it_config::Joints const> JointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gopher_move_it_config::Joints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gopher_move_it_config::Joints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gopher_move_it_config::Joints_<ContainerAllocator1> & lhs, const ::gopher_move_it_config::Joints_<ContainerAllocator2> & rhs)
{
  return lhs.joints == rhs.joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gopher_move_it_config::Joints_<ContainerAllocator1> & lhs, const ::gopher_move_it_config::Joints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gopher_move_it_config

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gopher_move_it_config::Joints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gopher_move_it_config::Joints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gopher_move_it_config::Joints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gopher_move_it_config::Joints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gopher_move_it_config::Joints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gopher_move_it_config::Joints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gopher_move_it_config::Joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82c16c802eb7e05fa5331a00ebfb3b28";
  }

  static const char* value(const ::gopher_move_it_config::Joints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82c16c802eb7e05fULL;
  static const uint64_t static_value2 = 0xa5331a00ebfb3b28ULL;
};

template<class ContainerAllocator>
struct DataType< ::gopher_move_it_config::Joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gopher_move_it_config/Joints";
  }

  static const char* value(const ::gopher_move_it_config::Joints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gopher_move_it_config::Joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joints\n"
;
  }

  static const char* value(const ::gopher_move_it_config::Joints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gopher_move_it_config::Joints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gopher_move_it_config::Joints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gopher_move_it_config::Joints_<ContainerAllocator>& v)
  {
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GOPHER_MOVE_IT_CONFIG_MESSAGE_JOINTS_H
