// Generated by gencpp from file gopher_move_it_config/PlanTrajectory.msg
// DO NOT EDIT!


#ifndef GOPHER_MOVE_IT_CONFIG_MESSAGE_PLANTRAJECTORY_H
#define GOPHER_MOVE_IT_CONFIG_MESSAGE_PLANTRAJECTORY_H

#include <ros/service_traits.h>


#include <gopher_move_it_config/PlanTrajectoryRequest.h>
#include <gopher_move_it_config/PlanTrajectoryResponse.h>


namespace gopher_move_it_config
{

struct PlanTrajectory
{

typedef PlanTrajectoryRequest Request;
typedef PlanTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanTrajectory
} // namespace gopher_move_it_config


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gopher_move_it_config::PlanTrajectory > {
  static const char* value()
  {
    return "66d002794b60389592f498a78cfe1427";
  }

  static const char* value(const ::gopher_move_it_config::PlanTrajectory&) { return value(); }
};

template<>
struct DataType< ::gopher_move_it_config::PlanTrajectory > {
  static const char* value()
  {
    return "gopher_move_it_config/PlanTrajectory";
  }

  static const char* value(const ::gopher_move_it_config::PlanTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::gopher_move_it_config::PlanTrajectoryRequest> should match
// service_traits::MD5Sum< ::gopher_move_it_config::PlanTrajectory >
template<>
struct MD5Sum< ::gopher_move_it_config::PlanTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gopher_move_it_config::PlanTrajectory >::value();
  }
  static const char* value(const ::gopher_move_it_config::PlanTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gopher_move_it_config::PlanTrajectoryRequest> should match
// service_traits::DataType< ::gopher_move_it_config::PlanTrajectory >
template<>
struct DataType< ::gopher_move_it_config::PlanTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::gopher_move_it_config::PlanTrajectory >::value();
  }
  static const char* value(const ::gopher_move_it_config::PlanTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gopher_move_it_config::PlanTrajectoryResponse> should match
// service_traits::MD5Sum< ::gopher_move_it_config::PlanTrajectory >
template<>
struct MD5Sum< ::gopher_move_it_config::PlanTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gopher_move_it_config::PlanTrajectory >::value();
  }
  static const char* value(const ::gopher_move_it_config::PlanTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gopher_move_it_config::PlanTrajectoryResponse> should match
// service_traits::DataType< ::gopher_move_it_config::PlanTrajectory >
template<>
struct DataType< ::gopher_move_it_config::PlanTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::gopher_move_it_config::PlanTrajectory >::value();
  }
  static const char* value(const ::gopher_move_it_config::PlanTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GOPHER_MOVE_IT_CONFIG_MESSAGE_PLANTRAJECTORY_H
